// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: test_rpc.proto

package server

import (
	"context"
	"grpc_study/test/test_rpc/internal/logic"
	"grpc_study/test/test_rpc/internal/svc"
	test_rpc2 "grpc_study/test/test_rpc/test_rpc"
)

type TestRpcServer struct {
	svcCtx *svc.ServiceContext
	test_rpc2.UnimplementedTestRpcServer
}

func NewTestRpcServer(svcCtx *svc.ServiceContext) *TestRpcServer {
	return &TestRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *TestRpcServer) Ping(ctx context.Context, in *test_rpc2.Request) (*test_rpc2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
